compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - "@openzeppelin=openzeppelin/openzeppelin-contracts@4.9.3/"
    vyper:
        version: null
dependencies:
    - openzeppelin/openzeppelin-contracts@4.9.3
    - uniswap/uniswap-v2-core@1.0.1